// @otoji/core entry — wraps the napi-rs native binding with a portable
// fallback so `npm install @otoji/core` works on every platform, even
// the ones we don't ship a prebuilt `.node` for.
//
// Resolution order:
//   1. Try to load the native binding (./index.js generated by napi-rs;
//      it picks the right `core.<triple>.node` or `@otoji/core-<triple>`
//      sub-package for process.platform/arch).
//   2. On failure (unsupported OS/arch, missing optional dep, etc.),
//      fall back to a pure-JS implementation.
//
// Fallback support:
//   - polishText:    full — calls Anthropic via global fetch.
//   - transcribePcm: not implementable without sherpa-onnx; throws a
//                    descriptive error pointing the user at the
//                    supported native targets.

"use strict";

let native = null;
let nativeLoadError = null;
try {
  // eslint-disable-next-line global-require
  native = require("./index.js");
} catch (e) {
  nativeLoadError = e;
}

const SUPPORTED = [
  "darwin-arm64",
  "darwin-x64",
  "linux-x64-gnu",
  "win32-x64-msvc",
];

const ANTHROPIC_URL = "https://api.anthropic.com/v1/messages";

async function polishTextFallback(opts) {
  if (!opts || !opts.apiKey) {
    throw new TypeError("polishText: opts.apiKey is required");
  }
  if (typeof opts.raw !== "string") {
    throw new TypeError("polishText: opts.raw must be a string");
  }
  if (typeof fetch !== "function") {
    throw new Error(
      "@otoji/core JS fallback needs a global `fetch` (Node 18+ / Bun / Deno)"
    );
  }
  const model = opts.model || "claude-haiku-4-5-20251001";
  const prev = opts.prev || "(none)";
  const system =
    "You tidy ASR transcripts.\n" +
    "- Preserve meaning. Do not summarize.\n" +
    "- Add punctuation, drop fillers (uh/um/那个/えーと).\n" +
    "- Normalize numbers, dates, units.\n" +
    "- Keep code-switched text (zh/en/ja) as-is.\n" +
    `- Previous sentence: ${prev}\n` +
    "Output only the tidied sentence.";
  const res = await fetch(ANTHROPIC_URL, {
    method: "POST",
    headers: {
      "x-api-key": opts.apiKey,
      "anthropic-version": "2023-06-01",
      "content-type": "application/json",
    },
    body: JSON.stringify({
      model,
      max_tokens: 512,
      system,
      messages: [{ role: "user", content: opts.raw }],
    }),
  });
  if (!res.ok) {
    const body = await res.text().catch(() => "");
    throw new Error(`anthropic ${res.status}: ${body}`);
  }
  const data = await res.json();
  return data.content
    .map((b) => b.text || "")
    .join("")
    .trim();
}

function transcribePcmFallback() {
  const platform = `${process.platform}-${process.arch}`;
  const reason = nativeLoadError ? ` (${nativeLoadError.message})` : "";
  throw new Error(
    `@otoji/core: transcribePcm requires the native binding, which is not ` +
      `available for ${platform}${reason}. ` +
      `Supported native targets: ${SUPPORTED.join(", ")}. ` +
      `polishText still works via the JS fallback.`
  );
}

module.exports.polishText =
  native && typeof native.polishText === "function"
    ? native.polishText
    : polishTextFallback;

module.exports.transcribePcm =
  native && typeof native.transcribePcm === "function"
    ? native.transcribePcm
    : transcribePcmFallback;

module.exports.isNativeAvailable = () => native !== null;
module.exports.nativeLoadError = () => nativeLoadError;
